[package]
name = "pmos"
version = "0.1.0"
authors = ["James Punnett <jppunnett@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
image = "0.23.12"